parameters:
  ite_js.notifications.sf_extension.class: ITE\Js\Notification\NotificationExtension
  ite_js.notifications.manager.class: ITE\Js\Notification\NotificationManager

services:
  ite_js.notifications.sf_extension:
    class: %ite_js.notifications.sf_extension.class%
    arguments: [@ite_js.notifications.manager]
    tags:
      - { name: ite_js.sf.extension, alias: 'notifications' }

  ite_js.notifications.manager:
    class: %ite_js.notifications.manager.class%
