parameters:
  ite_js.notifications.sf_extension.class: ITE\Js\Notification\NotificationSFExtension
  ite_js.notifications.notificator.class: ITE\Js\Notification\Notificator
  ite_js.notifications.channel.null.class: ITE\Js\Notification\Channel\NullChannel

services:
  ite_js.notifications.sf_extension:
    class: %ite_js.notifications.sf_extension.class%
    arguments: [@ite_js.notifications.notificator, %kernel.debug%]
    tags:
      - { name: ite_js.sf.extension, alias: 'notifications' }

  ite_js.notifications.notificator:
    class: %ite_js.notifications.notificator.class%
    arguments: [%ite_js.notifications.default_channel%]

  ite_notificator: "@ite_js.notifications.notificator"

  ite_js.notifications.channel.null:
    class: %ite_js.notifications.channel.null.class%
    tags:
      - { name: ite_js.notification.channel }
