parameters:
    ite_js.notification.collector.session.class: ITE\Js\Notification\Collector\SessionCollector

services:
    ite_js.notification.collector.session:
        class: %ite_js.notification.collector.session.class%
        arguments: [ @session, %ite_js.notification.collectors.session.channel_name% ]
        tags:
            - { name: ite_js.notifiaction.collector }
